BookWeb/BookWeb/Entities/Language.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace BookWeb.Entities
{
    public class Language
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string LanguageName { get; set; }
    }
}

BookWeb/BookWeb/Controllers/LanguageController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using BookWeb.Entities;
using BookWeb.Enums;
using BookWeb.Interfaces;
using BookWeb.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BookWeb.Controllers
{
    public class LanguageController : BaseController
    {
        private ILanguage _language;
        public LanguageController(ILanguage language)
        {
            _language = language;
        }

        public async Task<IActionResult> Index()
        {
            var model = await _language.GetAll();

            if (model != null)
                return View(model);
            return View();
        }
        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(Language language)
        {

            var createLanguage = await _language.AddAsync(language);

            if (createLanguage)
            {
                Alert("Language created successfully", NotificationType.success);
                return RedirectToAction("Index");
            }
            else
            {
                Alert("Language not created", NotificationType.error);
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var editLanguage = await _language.GetById(id);

            if (editLanguage == null)
            {
                return RedirectToAction("Index");
            }
            return View(editLanguage);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Language language)
        {
            var editLanguage = await _language.Update(language);

            if (editLanguage)
            {
                Alert("Language edited successfully", NotificationType.success);
                return RedirectToAction("Index");
            }
            else
            {
                Alert("Language not edited", NotificationType.error);
            }
            return View();
        }
        public async Task<IActionResult> Delete(int id)
        {
            var deleteLanguage = await _language.Delete(id);
            if (deleteLanguage)
            {
                Alert("Language deleted successfully", NotificationType.success);
                return RedirectToAction("Index");
            }
            else
            {
                Alert("Language not deleted", NotificationType.error);
            }
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BookWeb/BookWeb/Views/Language/Create.cshtml
@model BookWeb.Entities.Language
@{
    ViewData["Title"] = "Languages";
}

<div class="main-content" id="panel">
    <div class="container mt--8 pb-5">
        <div class="row justify-content-center" style="padding-top:200px;">
            <div class="col-lg-5 col-md-7">
                <div class="card bg-secondary border-0 mb-0">

                    <div class="card-body px-lg-5 py-lg-5">
                        <div class="text-center text-muted mb-4">
                            <small>New Language</small>
                        </div>
                        <form asp-controller="Language" method="post" role="form">
                            <div class="form-group mb-3">
                                <div class="input-group input-group-merge input-group-alternative">
                                    <input asp-for="LanguageName" class="form-control" placeholder="Language Name" required="">
                                </div>
                            </div>



                            <div class="text-center">
                                <button asp-action="Create" type="submit" class="btn btn-primary my-4">Create</button>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-6">
                        <a href="#" class="text-light"><small>Forgot password?</small></a>
                    </div>
                    <div class="col-6 text-right">
                        <a href="#" class="text-light"><small>Create new account</small></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

BookWeb/BookWeb/Views/Language/Edit.cshtml
@model BookWeb.Entities.Language
@{
    ViewData["Title"] = "Languages";
}

<div class="main-content" id="panel">
    <div class="container mt--8 pb-5">
        <div class="row justify-content-center" style="padding-top:200px;">
            <div class="col-lg-5 col-md-7">
                <div class="card bg-secondary border-0 mb-0">

                    <div class="card-body px-lg-5 py-lg-5">
                        <div class="text-center text-muted mb-4">
                            <small>New Language</small>
                        </div>
                        <form asp-controller="Language" method="post" role="form">
                            <div class="form-group mb-3">
                                <div class="input-group input-group-merge input-group-alternative">
                                    <input asp-for="LanguageName" class="form-control" placeholder="Language Name" required="">
                                </div>
                            </div>



                            <div class="text-center">
                                <button asp-action="Edit" type="submit" class="btn btn-primary my-4">Save Changes</button>
                            </div>
                        </form>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</div>

BookWeb/BookWeb/Views/Language/Index.cshtml
@model IEnumerable<BookWeb.Entities.Language>
@{
    ViewData["Title"] = "Languages";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="header bg-primary pb-6">
    <div class="container-fluid">
        <div class="header-body">
            <div class="row align-items-center py-4">
                <div class="col-lg-6 col-7">
                    <h6 class="h2 text-white d-inline-block mb-0">Tables</h6>
                    <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                        <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                            <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index"><i class="fas fa-home"></i></a></li>
                            @*<li class="breadcrumb-item"><a href="#">Tables</a></li>*@
                            <li class="breadcrumb-item active" aria-current="page">Languages</li>
                        </ol>
                    </nav>
                </div>
                <div class="col-lg-6 col-5 text-right">
                    <a asp-controller="Language" asp-action="Create" class="btn btn-sm btn-neutral">New Language</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid mt--6">

    <!-- Dark table -->
    <div class="row">
        <div class="col">
            <div class="card bg-default shadow">
                <div class="card-header bg-transparent border-0">
                    <h3 class="text-white mb-0">Languages</h3>
                </div>
                <div class="table-responsive">
                    <table class="table align-items-center table-dark table-flush">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col" class="sort" data-sort="name">Id</th>
                                <th scope="col" class="sort" data-sort="budget">Language Name</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody class="list">
                            @foreach (var language in Model)
                            {
                                <tr>
                                    <td>@language.Id</td>
                                    <td>@language.LanguageName</td>
                                    <td class="text-right">
                                        <div class="dropdown">
                                            <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <i class="fas fa-ellipsis-v"></i>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                <a class="dropdown-item" asp-action="Edit" asp-route-id="@language.Id">Edit</a>
                                                <a class="dropdown-item" asp-action="Delete" asp-route-id="@language.Id" onclick="return confirm('Are you sure you want to delete the language @language.LanguageName?')">Delete</a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>